export const DOCUMENT_UPLOAD_REQUEST ='DOCUMENT_UPLOAD_REQUEST'
export const DOCUMENT_UPLOAD_SUCCESS ='DOCUMENT_UPLOAD_SUCCESS'
export const DOCUMENT_UPLOAD_FAIL ='DOCUMENT_UPLOAD_FAIL'

export const DOCUMENT_LIST_REQUEST ='DOCUMENT_LIST_REQUEST'
export const DOCUMENT_LIST_SUCCESS ='DOCUMENT_LIST_SUCCESS'
export const DOCUMENT_LIST_FAIL ='DOCUMENT_LIST_FAIL'