export const ONBOARDING_REQUEST ='ONBOARDING_REQUEST'
export const ONBOARDING_SUCCESS ='ONBOARDING_SUCCESS'
export const ONBOARDING_FAIL ='ONBOARDING_FAIL'
export const ONBOARDING_RESET ='ONBOARDING_RESET'

export const FORM_REQUEST ='FORM_REQUEST'
export const FORM_SUCCESS ='FORM_SUCCESS'
export const FORM_FAIL ='FORM_FAIL'

export const ONBOARDING_ADD_REQUEST ='ONBOARDING_ADD_REQUEST'
export const ONBOARDING_ADD_SUCCESS ='ONBOARDING_ADD_SUCCESS'
export const ONBOARDING_ADD_FAIL ='ONBOARDING_ADD_FAIL'
